
file = tmp/HKQuantityTypeIdentifierAppleExerciseTime

plothr:
	python3 plot_heart.py tmp/HKQuantityTypeIdentifierHeartRate.hdf 

tohdf:
	python3 json2hdf.py ${file}.json	

parse:
	python3 parse.py ~/Dropbox/health/2019_12_30_apple/apple_health_export/export.xml